services:
  gateway-api: 
    build: ./services/gateway-api
    ports:
      - "8080:8080"
    environment:
      - JWT=${JWT-SECRET}
    depends_on:
      - auth-service
      - tasks-service
    networks:
      - frontend

  auth-service: 
    build: ./services/auth-service
    environment:
      - DB_HOST=auth-postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${AUTH_PASSWORD}
      - DB_NAME=${AUTH_DB}
      - JWT=${JWT-SECRET}
    depends_on:
      auth-postgres:
        condition: service_healthy
    networks:
      - frontend
      - backend

  auth-postgres: 
    image: postgres:17
    environment:
      - POSTGRES_DB=${AUTH_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${AUTH_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${AUTH_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - backend
    volumes:
      - pg_auth:/var/lib/postgresql/data

  tasks-service: 
    build: ./services/tasks-service
    environment:
      - USER=${DB_USER}
      - DB=${TASKS_DB}
      - PASSWORD=${TASKS_PASSWORD}
      - HOST=tasks_postgres
      - BROKER_URI=${BROKER_URI}
      - QUEUE_NAME=${QUEUE_NAME}
    depends_on:
      tasks-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./services/tasks-service/uploads:/app/uploads
    networks:
      - frontend
      - backend

  tasks-postgres: 
    image: postgres:17
    environment:
      - POSTGRES_DB=${TASKS_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${TASKS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${TASKS_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - backend
    volumes:
      - pg_tasks:/var/lib/postgresql/data

  rabbitmq: 
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  worker: #TODO 3 workers
    image: alpine

  file-service: #TODO
    image: alpine

  file-postgres: #TODO
    image: alpine

  notification-service: #TODO
    image: alpine

  notification-postgres: #TODO
    image: alpine

networks:
  frontend:
  backend:

volumes:
  rabbitmq_data:
  pg_tasks:
  pg_auth: